detection_server: 'http://127.0.0.1:8080/predictions/GravelDetectionYOLOv8s'
classification_server: 'http://127.0.0.2:8081/predictions/GravelClassificationDeit3s'
center_square_size: 200 # center_square_size_big/2